name: android-studio
version: "2023.3.1.18-Jellyfish"
summary: The IDE for Android
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.

  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.
grade: stable
confinement: classic
base: core22
compression: lzo
architectures:
  - build-on: amd64
apps:
  android-studio:
    command: bin/studio.sh
    environment:
      PULSE_SERVER: $XDG_RUNTIME_DIR/pulse/native
parts:
  android-studio:
    plugin: dump
    source: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.3.1.18/android-studio-2023.3.1.18-linux.tar.gz
    build-attributes:
      - no-patchelf
