name: android-studio
version: '3.0.1.0'
summary: IDE for Android
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.

  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.

grade: stable
confinement: classic
architectures:
  - amd64
  - i386

apps:
  android-studio:
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$SNAP/usr/lib32:$SNAP/lib32:$LD_LIBRARY_PATH
    command: android-studio/bin/studio.sh
    desktop: jetbrains-studio.desktop

parts:
  enable-i386:
    plugin: nil
    prepare: |
      dpkg --add-architecture i386
      apt update
  desktop:
    after:
      - android-studio
    plugin: dump
    source: .
    prime:
      - jetbrains-studio.desktop
  android-studio:
    after: [enable-i386]
    plugin: dump
    source: https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip
    stage-packages:
      - libxrender1
      - libxtst6
      - libxi6
      - on amd64:
        - libc6:i386
        - libncurses5:i386
        - libstdc++6:i386
        - libbz2-1.0:i386
        - lib32z1
