name: Update

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync version with upstream
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Sync version with upstream
        uses: snapcrafters/ci/sync-version@main
        with:
          token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          update-script: |
            release_page="$(curl -sL https://developer.android.com/studio/releases)"
            source_url="$(printf '%s' "$release_page" | grep -oP 'https://edgedl\.me\.gvt1\.com/android/studio/ide-zips/\d+\.\d+\.\d+\.\d+/android-studio-[^"]+-linux\.tar\.gz' | head -n1)"
            source_version="$(printf '%s' "$source_url" | sed -E 's#^.*/ide-zips/([0-9.]+)/.*#\1#')"
            source_file="$(basename "$source_url" .tar.gz)"
            version="${source_version}-$(printf '%s' "$source_file" | sed -E 's/^android-studio-//; s/-linux$//')"
            sed -i "s|source: .*$|source: $source_url|g" snap/snapcraft.yaml 
            sed -i 's/^\(version: \).*$/\1'"\"$version\""'/' snap/snapcraft.yaml
